namespace PicoDI.Gen;

internal static class OpenGenericMetadataContract
{
    /// <summary>
    /// Discovers open generic registrations from referenced assemblies by scanning for
    /// PicoDiOpenGenericMetadata classes generated by the source generator.
    /// </summary>
    public static List<OpenGenericRegistration> DiscoverOpenGenericsFromReferencedAssemblies(
        Compilation compilation,
        List<OpenGenericRegistration> existingOpenGenerics
    )
    {
        var discovered = new List<OpenGenericRegistration>();
        var existingOpenNames = new HashSet<string>(
            existingOpenGenerics.Select(og => og.OpenServiceTypeFullName)
        );

        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly)
                continue;

            var metadataTypes = FindMetadataTypes(assembly.GlobalNamespace);
            foreach (
                var registration in metadataTypes
                    .Select(ExtractOpenGenericRegistrationsFromMetadata)
                    .SelectMany(registrations =>
                        registrations.Where(reg =>
                            !existingOpenNames.Contains(reg.OpenServiceTypeFullName)
                        )
                    )
            )
            {
                discovered.Add(registration);
                existingOpenNames.Add(registration.OpenServiceTypeFullName);
            }
        }

        return discovered;
    }

    public static string GenerateOpenGenericMetadata(List<OpenGenericRegistration> openGenerics)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PicoDI.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Metadata class containing open generic registrations from this assembly."
        );
        sb.AppendLine(
            "/// This is auto-generated by PicoDI.Gen and used by other assemblies to discover"
        );
        sb.AppendLine("/// open generic mappings at compile time.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine(
            "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        sb.AppendLine("public static class PicoDiOpenGenericMetadata");
        sb.AppendLine("{");

        var index = 0;
        foreach (var openGeneric in openGenerics)
        {
            AppendOpenGenericMetadataRegistration(sb, openGeneric, index);
            index++;
        }

        sb.AppendLine("}");
        sb.AppendLine();
        AppendPicoDiOpenGenericAttributeDefinition(sb);

        return sb.ToString();
    }

    private static List<INamedTypeSymbol> FindMetadataTypes(INamespaceSymbol ns)
    {
        var result = new List<INamedTypeSymbol>();

        foreach (var type in ns.GetTypeMembers())
        {
            if (
                type.Name == "PicoDiOpenGenericMetadata"
                && type.DeclaredAccessibility == Accessibility.Public
            )
            {
                result.Add(type);
            }
        }

        foreach (var childNs in ns.GetNamespaceMembers())
        {
            result.AddRange(FindMetadataTypes(childNs));
        }

        return result;
    }

    private static List<OpenGenericRegistration> ExtractOpenGenericRegistrationsFromMetadata(
        INamedTypeSymbol metadataType
    )
    {
        var result = new List<OpenGenericRegistration>();

        foreach (var member in metadataType.GetMembers())
        {
            if (member is not IFieldSymbol field || !field.IsStatic || !field.IsReadOnly)
                continue;

            foreach (var attr in field.GetAttributes())
            {
                if (attr.AttributeClass?.Name != "PicoDiOpenGenericAttribute")
                    continue;

                var args = attr.ConstructorArguments;
                if (args.Length < 4)
                    continue;

                var serviceType = args[0].Value as string ?? "";
                var implementationType = args[1].Value as string ?? "";
                var lifetime = args[2].Value as string ?? "Singleton";
                var typeParameterCount = (int)(args[3].Value ?? 1);

                var typeParameterNames = ImmutableArray<string>.Empty;
                var constructorParameters = ImmutableArray<string>.Empty;

                foreach (var namedArg in attr.NamedArguments)
                {
                    switch (namedArg.Key)
                    {
                        case "TypeParameterNames" when namedArg.Value.Values.Length > 0:
                            typeParameterNames =
                            [
                                .. namedArg.Value.Values.Select(v => v.Value as string ?? "T"),
                            ];
                            break;
                        case "ConstructorParameters" when namedArg.Value.Values.Length > 0:
                            constructorParameters =
                            [
                                .. namedArg.Value.Values.Select(v => v.Value as string ?? ""),
                            ];
                            break;
                    }
                }

                if (typeParameterNames.IsEmpty)
                {
                    typeParameterNames =
                    [
                        .. Enumerable
                            .Range(0, typeParameterCount)
                            .Select(i => i is 0 ? "T" : $"T{i}"),
                    ];
                }

                result.Add(
                    new OpenGenericRegistration(
                        serviceType,
                        implementationType,
                        lifetime,
                        typeParameterCount,
                        typeParameterNames,
                        constructorParameters,
                        ImmutableArray<ITypeSymbol>.Empty
                    )
                );
            }
        }

        return result;
    }

    private static void AppendOpenGenericMetadataRegistration(
        StringBuilder sb,
        OpenGenericRegistration openGeneric,
        int index
    )
    {
        var typeParameterNames = string.Join("\", \"", openGeneric.TypeParameterNames);

        sb.AppendLine(
            $"    /// <summary>Open generic mapping: {EscapeXml(openGeneric.OpenServiceTypeFullName)} -&gt; {EscapeXml(openGeneric.OpenImplementationTypeFullName)}</summary>"
        );

        if (openGeneric.ConstructorParameters.Length > 0)
        {
            var constructorParameters = string.Join("\", \"", openGeneric.ConstructorParameters);
            sb.AppendLine(
                $"    [PicoDiOpenGeneric(\"{openGeneric.OpenServiceTypeFullName}\", \"{openGeneric.OpenImplementationTypeFullName}\", \"{openGeneric.Lifetime}\", {openGeneric.TypeParameterCount},"
            );
            sb.AppendLine($"        TypeParameterNames = new[] {{ \"{typeParameterNames}\" }},");
            sb.AppendLine(
                $"        ConstructorParameters = new[] {{ \"{constructorParameters}\" }})]"
            );
        }
        else
        {
            sb.AppendLine(
                $"    [PicoDiOpenGeneric(\"{openGeneric.OpenServiceTypeFullName}\", \"{openGeneric.OpenImplementationTypeFullName}\", \"{openGeneric.Lifetime}\", {openGeneric.TypeParameterCount},"
            );
            sb.AppendLine($"        TypeParameterNames = new[] {{ \"{typeParameterNames}\" }})]");
        }

        sb.AppendLine($"    public static readonly int Registration{index};");
        sb.AppendLine();
    }

    private static string EscapeXml(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static void AppendPicoDiOpenGenericAttributeDefinition(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Attribute used to store open generic registration metadata.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine(
            "[global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false)]"
        );
        sb.AppendLine(
            "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        sb.AppendLine(
            "internal sealed class PicoDiOpenGenericAttribute : global::System.Attribute"
        );
        sb.AppendLine("{");
        sb.AppendLine("    public string ServiceType { get; }");
        sb.AppendLine("    public string ImplementationType { get; }");
        sb.AppendLine("    public string Lifetime { get; }");
        sb.AppendLine("    public int TypeParameterCount { get; }");
        sb.AppendLine("    public string[]? TypeParameterNames { get; set; }");
        sb.AppendLine("    public string[]? ConstructorParameters { get; set; }");
        sb.AppendLine();
        sb.AppendLine(
            "    public PicoDiOpenGenericAttribute(string serviceType, string implementationType, string lifetime, int typeParameterCount)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        ServiceType = serviceType;");
        sb.AppendLine("        ImplementationType = implementationType;");
        sb.AppendLine("        Lifetime = lifetime;");
        sb.AppendLine("        TypeParameterCount = typeParameterCount;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }
}
