namespace PicoMediator.Gen;

[Generator(LanguageNames.CSharp)]
public sealed class MediatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax c && c.BaseList?.Types.Count > 0,
                transform: static (ctx, ct) => GetHandlerInfos(ctx, ct)
            )
            .Where(static x => x.Length > 0)
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(
            handlerDeclarations.Collect(),
            static (spc, handlers) => GenerateDispatch(spc, handlers)
        );
    }

    private enum HandlerKind
    {
        Command,
        Subscribe,
    }

    private static ImmutableArray<HandlerInfo> GetHandlerInfos(
        GeneratorSyntaxContext ctx,
        CancellationToken ct
    )
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl)
            return [];

        var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        if (typeSymbol is null || typeSymbol.IsAbstract || typeSymbol.IsGenericType)
            return [];

        var results = ImmutableArray.CreateBuilder<HandlerInfo>();
        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
                continue;

            var constructed = iface.ConstructedFrom;
            if (constructed.ContainingNamespace.ToDisplayString() != "PicoMediator.Abs")
                continue;

            if (constructed.MetadataName == "ICommandHandler`2")
            {
                results.Add(
                    new HandlerInfo(
                        HandlerKind.Command,
                        iface
                            .TypeArguments[0]
                            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        iface
                            .TypeArguments[1]
                            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    )
                );
            }
            else if (constructed.MetadataName == "ISubscriber`1")
            {
                results.Add(
                    new HandlerInfo(
                        HandlerKind.Subscribe,
                        iface
                            .TypeArguments[0]
                            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        null
                    )
                );
            }
        }

        return results.ToImmutable();
    }

    private static void GenerateDispatch(
        SourceProductionContext context,
        ImmutableArray<HandlerInfo> handlers
    )
    {
        var commands = new List<HandlerInfo>();
        foreach (var h in handlers)
        {
            if (h.Kind == HandlerKind.Command)
                commands.Add(h);
        }

        // Subscribers only: no switch file in this task — the registrations
        // file (Task 3) carries them. Emit the switch only when commands exist.
        if (commands.Count is 0)
            return;

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Found {commands.Count} command handler(s)");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace PicoMediator.Generated;");
        sb.AppendLine();

        sb.AppendLine("internal static class MediatorSwitchDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    internal static object? Dispatch(");
        sb.AppendLine("        global::System.Type requestType,");
        sb.AppendLine("        global::PicoDI.Abs.ISvcScope scope,");
        sb.AppendLine("        object request,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (request)");
        sb.AppendLine("        {");

        foreach (var h in commands)
        {
            AppendTypedCommandCase(sb, h);
        }

        sb.AppendLine("        }");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ModuleInitializer wires it into GeneratedDispatch via RegisterSwitch
        sb.AppendLine("internal static class MediatorSwitchInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Init()");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        global::PicoMediator.GeneratedDispatch.RegisterSwitch(MediatorSwitchDispatch.Dispatch);"
        );
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("MediatorSwitch.g.cs", sb.ToString());
    }

    private static void AppendTypedCommandCase(StringBuilder sb, HandlerInfo h)
    {
        var handlerType =
            $"global::PicoMediator.Abs.ICommandHandler<{h.RequestType}, {h.ResponseType}>";
        sb.AppendLine($"            case {h.RequestType} typed:");
        sb.AppendLine("            {");
        sb.AppendLine($"                var handler = ({handlerType})");
        sb.AppendLine($"                    scope.GetService(typeof({handlerType}));");
        sb.AppendLine("                if (handler is null)");
        sb.AppendLine("                    return null; // fall through to runtime dispatch");
        sb.AppendLine("                var vt = handler.Handle(typed, ct);");
        sb.AppendLine("                return vt; // boxed as object");
        sb.AppendLine("            }");
    }

    private sealed class HandlerInfo
    {
        public HandlerKind Kind { get; }
        public string RequestType { get; }
        public string? ResponseType { get; }

        public HandlerInfo(HandlerKind kind, string requestType, string? responseType)
        {
            Kind = kind;
            RequestType = requestType;
            ResponseType = responseType;
        }
    }
}
