using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PicoMediator.Gen;

[Generator(LanguageNames.CSharp)]
public sealed class MediatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax c && c.BaseList?.Types.Count > 0,
                transform: static (ctx, ct) => GetHandlerInfo(ctx, ct)
            )
            .Where(static x => x is not null);

        context.RegisterSourceOutput(
            handlerDeclarations.Collect(),
            static (spc, handlers) => GenerateDispatch(spc, handlers)
        );
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl)
            return null;

        var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        if (typeSymbol is null || typeSymbol.IsAbstract)
            return null;

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
                continue;

            var openType = iface.ConstructedFrom;
            if (
                openType.ToDisplayString()
                is not "PicoMediator.Abs.IRequestHandler<TRequest, TResponse>"
            )
                continue;

            return new HandlerInfo(
                iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                iface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            );
        }

        return null;
    }

    private static void GenerateDispatch(
        SourceProductionContext context,
        ImmutableArray<HandlerInfo?> handlers
    )
    {
        var valid = new List<HandlerInfo>();
        foreach (var h in handlers)
        {
            if (h is not null)
                valid.Add(h);
        }

        if (valid.Count == 0)
            return;

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace PicoMediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedMediatorDispatch");
        sb.AppendLine("{");
        sb.AppendLine(
            "    internal static global::System.Threading.Tasks.ValueTask<TResponse> Send<TRequest, TResponse>("
        );
        sb.AppendLine(
            "        global::PicoDI.Abs.ISvcScope scope, TRequest request, global::System.Threading.CancellationToken ct)"
        );
        sb.AppendLine("        where TRequest : global::PicoMediator.Abs.IRequest<TResponse>");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (request)");
        sb.AppendLine("        {");

        foreach (var h in valid)
        {
            sb.AppendLine($"            case {h.RequestType} _:");
            sb.AppendLine("            {");
            sb.AppendLine(
                $"                var handler = scope.GetService<global::PicoMediator.Abs.IRequestHandler<{h.RequestType}, {h.ResponseType}>>();"
            );
            sb.AppendLine(
                $"                var vt = handler.Handle(({h.RequestType})(object)request!, ct);"
            );
            sb.AppendLine($"                return UnsafeCast<{h.ResponseType}, TResponse>(vt);");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(
            "        var fallback = scope.GetService<global::PicoMediator.Abs.IRequestHandler<TRequest, TResponse>>();"
        );
        sb.AppendLine("        if (fallback is not null)");
        sb.AppendLine("            return fallback.Handle(request, ct);");
        sb.AppendLine();
        sb.AppendLine("        throw new global::System.InvalidOperationException(");
        sb.AppendLine("            $\"No handler registered for {typeof(TRequest).FullName}.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine(
            "    private static global::System.Threading.Tasks.ValueTask<TResponse> UnsafeCast<TActual, TResponse>("
        );
        sb.AppendLine("        global::System.Threading.Tasks.ValueTask<TActual> vt)");
        sb.AppendLine(
            "        => global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<TActual>, global::System.Threading.Tasks.ValueTask<TResponse>>(ref vt);"
        );
        sb.AppendLine("}");

        context.AddSource("GeneratedMediatorDispatch.g.cs", sb.ToString());
    }

    private sealed class HandlerInfo
    {
        public string RequestType { get; }
        public string ResponseType { get; }

        public HandlerInfo(string requestType, string responseType)
        {
            RequestType = requestType;
            ResponseType = responseType;
        }
    }
}
