namespace PicoMediator.Gen;

[Generator(LanguageNames.CSharp)]
public sealed class MediatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax c && c.BaseList?.Types.Count > 0,
                transform: static (ctx, ct) => GetHandlerInfos(ctx, ct)
            )
            .Where(static x => x.Length > 0)
            .SelectMany(static (x, _) => x);

        context.RegisterSourceOutput(
            handlerDeclarations.Collect(),
            static (spc, handlers) => GenerateDispatch(spc, handlers)
        );

        var combined = context.CompilationProvider.Combine(handlerDeclarations.Collect());

        context.RegisterSourceOutput(
            combined,
            static (spc, pair) => GenerateRegistrations(spc, pair.Left, pair.Right)
        );
    }

    private enum HandlerKind
    {
        Command,
        Subscribe,
    }

    private static ImmutableArray<HandlerInfo> GetHandlerInfos(
        GeneratorSyntaxContext ctx,
        CancellationToken ct
    )
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl)
            return [];

        var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        var accessibility = typeSymbol?.DeclaredAccessibility;
        if (
            typeSymbol is null
            || typeSymbol.IsAbstract
            || typeSymbol.IsGenericType
            // Private/protected nested classes cannot be instantiated by the
            // generated code (same assembly access only) — skip them.
            || (accessibility != Accessibility.Public && accessibility != Accessibility.Internal)
        )
            return [];

        var results = ImmutableArray.CreateBuilder<HandlerInfo>();
        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType)
                continue;

            var constructed = iface.ConstructedFrom;
            if (constructed.ContainingNamespace.ToDisplayString() != "PicoMediator.Abs")
                continue;

            if (constructed.MetadataName == "ICommandHandler`2")
            {
                results.Add(CreateHandlerInfo(HandlerKind.Command, typeSymbol, iface));
            }
            else if (constructed.MetadataName == "ISubscriber`1")
            {
                results.Add(CreateHandlerInfo(HandlerKind.Subscribe, typeSymbol, iface));
            }
        }

        return results.ToImmutable();
    }

    private static HandlerInfo CreateHandlerInfo(
        HandlerKind kind,
        INamedTypeSymbol typeSymbol,
        INamedTypeSymbol iface
    )
    {
        // First public instance ctor wins; ambiguous ctors are the author's
        // responsibility. No public ctor (e.g. internal default ctor) -> no
        // arguments (generated code is in the same assembly, so `new Impl()`
        // still works).
        var ctor = typeSymbol.InstanceConstructors.FirstOrDefault(c =>
            c.DeclaredAccessibility == Accessibility.Public && !c.IsStatic
        );
        var ctorParams = ctor is null
            ? []
            : ctor
                .Parameters.Select(p =>
                    p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                )
                .ToImmutableArray();

        return new HandlerInfo(
            kind,
            iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            kind == HandlerKind.Command
                ? iface.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : null,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            ctorParams
        );
    }

    private static void GenerateRegistrations(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<HandlerInfo> handlers
    )
    {
        if (handlers.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = SanitizeIdentifier(assemblyName);
        var className = $"MediatorHandlerRegistrations_{safeAssemblyName}";
        var configuratorId = $"pico-mediator::{assemblyName}::{className}";

        var sb = new StringBuilder(8192);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace PicoMediator.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class " + className);
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void AutoRegister()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::PicoMediator.MediatorAutoSubscriptionRegistry.Register(");
        sb.AppendLine(
            $"            \"{EscapeStringLiteral(configuratorId)}\", static container => ConfigureGeneratedHandlers(container));"
        );
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine(
            "    internal static void ConfigureGeneratedHandlers(global::PicoDI.Abs.ISvcContainer container)"
        );
        sb.AppendLine("    {");

        foreach (var h in handlers)
        {
            var serviceType =
                h.Kind == HandlerKind.Command
                    ? $"global::PicoMediator.Abs.ICommandHandler<{h.RequestType}, {h.ResponseType}>"
                    : $"global::PicoMediator.Abs.ISubscriber<{h.RequestType}>";

            sb.AppendLine($"        if (!container.IsRegistered(typeof({serviceType})))");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            container.Register(global::PicoDI.Abs.SvcDescriptor.Create("
            );
            sb.AppendLine($"                typeof({serviceType}),");
            sb.AppendLine($"                {EmitFactory(h)},");
            sb.AppendLine("                global::PicoDI.Abs.SvcLifetime.Transient));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource($"MediatorHandlerRegistrations.{safeAssemblyName}.g.cs", sb.ToString());
    }

    private static string EmitFactory(HandlerInfo h)
    {
        if (h.ConstructorParameterTypes.IsEmpty)
            return $"static _ => new {h.ImplementationType}()";

        var args = string.Join(
            ", ",
            h.ConstructorParameterTypes.Select(p => $"({p})scope.GetService(typeof({p}))")
        );
        return $"static scope => new {h.ImplementationType}({args})";
    }

    private static string SanitizeIdentifier(string value) =>
        new(
            value
                .Select(c => c == '.' ? '_' : c)
                .Where(static c => char.IsLetterOrDigit(c) || c == '_')
                .ToArray()
        );

    private static string EscapeStringLiteral(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static void GenerateDispatch(
        SourceProductionContext context,
        ImmutableArray<HandlerInfo> handlers
    )
    {
        var commands = new List<HandlerInfo>();
        foreach (var h in handlers)
        {
            if (h.Kind == HandlerKind.Command)
                commands.Add(h);
        }

        // Subscribers only: no switch file in this task — the registrations
        // file (Task 3) carries them. Emit the switch only when commands exist.
        if (commands.Count is 0)
            return;

        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Found {commands.Count} command handler(s)");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace PicoMediator.Generated;");
        sb.AppendLine();

        sb.AppendLine("internal static class MediatorSwitchDispatch");
        sb.AppendLine("{");
        sb.AppendLine("    internal static object? Dispatch(");
        sb.AppendLine("        global::System.Type requestType,");
        sb.AppendLine("        global::PicoDI.Abs.ISvcScope scope,");
        sb.AppendLine("        object request,");
        sb.AppendLine("        global::System.Threading.CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (request)");
        sb.AppendLine("        {");

        foreach (var h in commands)
        {
            AppendTypedCommandCase(sb, h);
        }

        sb.AppendLine("        }");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ModuleInitializer wires it into GeneratedDispatch via RegisterSwitch
        sb.AppendLine("internal static class MediatorSwitchInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Init()");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        global::PicoMediator.GeneratedDispatch.RegisterSwitch(MediatorSwitchDispatch.Dispatch);"
        );
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("MediatorSwitch.g.cs", sb.ToString());
    }

    private static void AppendTypedCommandCase(StringBuilder sb, HandlerInfo h)
    {
        var handlerType =
            $"global::PicoMediator.Abs.ICommandHandler<{h.RequestType}, {h.ResponseType}>";
        sb.AppendLine($"            case {h.RequestType} typed:");
        sb.AppendLine("            {");
        sb.AppendLine($"                var handler = ({handlerType})");
        sb.AppendLine($"                    scope.GetService(typeof({handlerType}));");
        sb.AppendLine("                if (handler is null)");
        sb.AppendLine("                    return null; // fall through to runtime dispatch");
        sb.AppendLine("                var vt = handler.Handle(typed, ct);");
        sb.AppendLine("                return vt; // boxed as object");
        sb.AppendLine("            }");
    }

    private sealed class HandlerInfo
    {
        public HandlerKind Kind { get; }
        public string RequestType { get; }
        public string? ResponseType { get; }
        public string ImplementationType { get; }
        public ImmutableArray<string> ConstructorParameterTypes { get; }

        public HandlerInfo(
            HandlerKind kind,
            string requestType,
            string? responseType,
            string implementationType,
            ImmutableArray<string> constructorParameterTypes
        )
        {
            Kind = kind;
            RequestType = requestType;
            ResponseType = responseType;
            ImplementationType = implementationType;
            ConstructorParameterTypes = constructorParameterTypes;
        }
    }
}
