[assembly: InternalsVisibleTo("PicoCfg.Tests")]
[assembly: InternalsVisibleTo("PicoCfg.DI")]
[assembly: InternalsVisibleTo("PicoCfg.DI.Tests")]
[assembly: InternalsVisibleTo("PicoCfg.Gen.Tests")]
[assembly: InternalsVisibleTo("PicoCfg.Json")]
[assembly: InternalsVisibleTo("PicoCfg.Yaml")]
[assembly: InternalsVisibleTo("PicoCfg.Ini")]
[assembly: InternalsVisibleTo("PicoCfg.Toml")]
