using Microsoft.CodeAnalysis.Text;
using PicoAop.Gen.Emission;

namespace PicoAop.Gen;

[Generator(LanguageNames.CSharp)]
public sealed partial class InterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interceptionCalls = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => InterceptorSyntax.IsInterceptByInvocation(node),
                transform: static (ctx, ct) => InterceptorSyntax.ExtractInterceptionInfo(ctx, ct))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(
            interceptionCalls.Collect(),
            static (spc, infos) => Generate(spc, infos));
    }

    private static void Generate(
        SourceProductionContext spc,
        ImmutableArray<InterceptionInfo?> infos)
    {
        var deduped = infos.OfType<InterceptionInfo>()
            .Distinct()
            .ToList();

        if (deduped.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {PicoAopNames.GeneratedNamespace};");
        sb.AppendLine("using global::PicoAop.Abs;");
        sb.AppendLine();

        var wrappersSb = new StringBuilder();
        wrappersSb.AppendLine("// <auto-generated/>");
        wrappersSb.AppendLine("#nullable enable");
        wrappersSb.AppendLine($"namespace {PicoAopNames.GeneratedNamespace};");

        foreach (var info in deduped)
        {
            if (info.ServiceType is not INamedTypeSymbol svcType)
                continue;

            // Validate
            if (svcType.IsSealed)
            { spc.ReportDiagnostic(Diagnostic.Create(PicoAopDiag.SealedType, Location.None, svcType.Name)); continue; }
            if (svcType.IsValueType)
            { spc.ReportDiagnostic(Diagnostic.Create(PicoAopDiag.ValueType, Location.None, svcType.Name)); continue; }

            var safeSvc = InvocationEmitter.BuildSafeServiceName(svcType);
            var methods = svcType.GetMembers().OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary
                    && m.DeclaredAccessibility == Accessibility.Public
                    && !m.IsStatic);

            // Emit Invocation structs
            foreach (var method in methods)
            {
                if (method.Parameters.Any(p => p.RefKind != RefKind.None))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(PicoAopDiag.RefOutMethod,
                        Location.None, method.Name, svcType.Name));
                    continue;
                }
                sb.AppendLine(InvocationEmitter.EmitInvocationStruct(
                    safeSvc, method.Name, method, info.InterceptorType));
            }

            // Property getter/setter structs
            foreach (var prop in svcType.GetMembers().OfType<IPropertySymbol>()
                .Where(p => !p.IsIndexer && !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public))
            {
                EmitPropertyStructs(sb, safeSvc, prop, svcType, info.InterceptorType);
            }

            // Proxy class
            sb.AppendLine(ProxyEmitter.EmitInterceptedClass(
                safeSvc, svcType, info.InterceptorType));

            // Wrapper factory
            wrappersSb.Append(ProxyEmitter.EmitWrappersClass(
                safeSvc, svcType, info.InterceptorType));
        }

        spc.AddSource("PicoAop.Invocations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        spc.AddSource("PicoAop.Wrappers.g.cs", SourceText.From(wrappersSb.ToString(), Encoding.UTF8));
    }

    private static void EmitPropertyStructs(
        StringBuilder sb, string safeSvcName,
        IPropertySymbol prop, INamedTypeSymbol serviceType, ITypeSymbol interceptorType)
    {
        var svcFullName = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var intFullName = interceptorType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var intSuffix = $"_{InvocationEmitter.Sanitize(interceptorType.Name)}";

        if (prop.GetMethod?.DeclaredAccessibility == Accessibility.Public)
        {
            sb.AppendLine($"struct Invocation_{safeSvcName}_{prop.Name}_Getter{intSuffix} : IInvocation<{propType}>");
            sb.AppendLine("{");
            sb.AppendLine($"    internal readonly {svcFullName} _target;");
            sb.AppendLine($"    internal readonly {intFullName} _i0;");
            sb.AppendLine($"    public string MethodName => \"get_{prop.Name}\";");
            sb.AppendLine($"    public Type ServiceType => typeof({svcFullName});");
            sb.AppendLine($"    public {propType} Result {{ get; set; }}");
            sb.AppendLine($"    internal {propType} InvokeTarget() => _target.{prop.Name};");
            sb.AppendLine("}");
        }

        if (prop.SetMethod?.DeclaredAccessibility == Accessibility.Public && !prop.SetMethod.IsInitOnly)
        {
            sb.AppendLine($"struct Invocation_{safeSvcName}_{prop.Name}_Setter{intSuffix} : IInvocation");
            sb.AppendLine("{");
            sb.AppendLine($"    internal readonly {svcFullName} _target;");
            sb.AppendLine($"    internal readonly {intFullName} _i0;");
            sb.AppendLine($"    internal readonly {propType} _value;");
            sb.AppendLine($"    public string MethodName => \"set_{prop.Name}\";");
            sb.AppendLine($"    public Type ServiceType => typeof({svcFullName});");
            sb.AppendLine($"    internal void InvokeTarget() => _target.{prop.Name} = _value;");
            sb.AppendLine("}");
        }
    }
}
