using Microsoft.CodeAnalysis.Text;
using PicoAop.Gen.Emission;

namespace PicoAop.Gen;

[Generator(LanguageNames.CSharp)]
public sealed partial class InterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interceptionCalls = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => InterceptorSyntax.IsInterceptByInvocation(node),
                transform: static (ctx, ct) => InterceptorSyntax.ExtractInterceptionInfo(ctx, ct))
            .Where(static info => info is not null);

        var globalCalls = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => InterceptorSyntax.IsAddInterceptorInvocation(node),
                transform: static (ctx, ct) => InterceptorSyntax.ExtractGlobalInterceptorInfo(ctx, ct))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(
            interceptionCalls.Collect().Combine(globalCalls.Collect()),
            static (spc, source) => Generate(spc, source.Left, source.Right));
    }

    private static void Generate(
        SourceProductionContext spc,
        ImmutableArray<InterceptionInfo?> infos,
        ImmutableArray<GlobalInterceptorInfo?> globals)
    {
        var comparer = SymbolEqualityComparer.Default;

        // Collect global interceptors
        var globalInts = new List<ITypeSymbol>();
        foreach (var g in globals.OfType<GlobalInterceptorInfo>())
        {
            if (g.InterceptorType != null && !globalInts.Any(i => comparer.Equals(i, g.InterceptorType)))
                globalInts.Add(g.InterceptorType);
        }

        // Merge by service type using a dictionary
        var serviceMap = new Dictionary<ITypeSymbol, List<ITypeSymbol>>(comparer);
        foreach (var info in infos.OfType<InterceptionInfo>())
        {
            if (info.ServiceType == null) continue;
            if (!serviceMap.TryGetValue(info.ServiceType, out var ints))
                serviceMap[info.ServiceType] = ints = new List<ITypeSymbol>();
            if (!ints.Any(i => comparer.Equals(i, info.InterceptorType)))
                ints.Add(info.InterceptorType);
        }

        // Apply global interceptors to ALL services
        if (globalInts.Count > 0)
        {
            foreach (var ints in serviceMap.Values)
            {
                foreach (var g in globalInts)
                {
                    if (!ints.Any(i => comparer.Equals(i, g)))
                        ints.Add(g);
                }
            }
        }

        if (serviceMap.Count == 0)
            return;

        var grouped = serviceMap.Select(kvp => (ServiceType: kvp.Key, InterceptorTypes: kvp.Value)).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {PicoAopNames.GeneratedNamespace};");
        sb.AppendLine("using global::PicoAop.Abs;");
        sb.AppendLine();

        var wrappersSb = new StringBuilder();
        wrappersSb.AppendLine("// <auto-generated/>");
        wrappersSb.AppendLine("#nullable enable");
        wrappersSb.AppendLine($"namespace {PicoAopNames.GeneratedNamespace};");

        foreach (var (svcType, interceptorTypes) in grouped)
        {
            if (svcType is not INamedTypeSymbol namedSvc)
                continue;

            if (namedSvc.IsSealed)
            { spc.ReportDiagnostic(Diagnostic.Create(PicoAopDiag.SealedType, Location.None, namedSvc.Name)); continue; }
            if (namedSvc.IsValueType)
            { spc.ReportDiagnostic(Diagnostic.Create(PicoAopDiag.ValueType, Location.None, namedSvc.Name)); continue; }

            var safeSvc = InvocationEmitter.BuildSafeServiceName(namedSvc);
            var methods = namedSvc.GetMembers().OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary
                    && m.DeclaredAccessibility == Accessibility.Public
                    && !m.IsStatic);

            // Emit Invocation structs with _i0.._iN fields
            foreach (var method in methods)
            {
                if (method.Parameters.Any(p => p.RefKind != RefKind.None))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(PicoAopDiag.RefOutMethod,
                        Location.None, method.Name, namedSvc.Name));
                    continue;
                }
                sb.AppendLine(EmitMultiInvocationStruct(safeSvc, method, interceptorTypes));
            }

            // Property getter/setter structs
            foreach (var prop in namedSvc.GetMembers().OfType<IPropertySymbol>()
                .Where(p => !p.IsIndexer && !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public))
            {
                EmitPropertyStructs(sb, safeSvc, prop, namedSvc, interceptorTypes);
            }

            // Proxy class with all interceptors
            sb.AppendLine(ProxyEmitter.EmitInterceptedClassMulti(
                safeSvc, namedSvc, interceptorTypes));

            // Wrapper factory
            wrappersSb.Append(EmitMultiWrappers(safeSvc, namedSvc, interceptorTypes));
        }

        if (sb.Length > 0)
            spc.AddSource("PicoAop.Invocations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        if (wrappersSb.Length > 0)
            spc.AddSource("PicoAop.Wrappers.g.cs", SourceText.From(wrappersSb.ToString(), Encoding.UTF8));
    }

    private static string EmitMultiInvocationStruct(
        string safeSvcName, IMethodSymbol method, List<ITypeSymbol> interceptorTypes)
    {
        var sb = new StringBuilder();
        var svcFullName = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var retType = method.ReturnType;
        var retNamed = retType as INamedTypeSymbol;
        var metaName = retNamed?.MetadataName;

        var isAsync = metaName is "Task`1" or "ValueTask`1" or "Task" or "ValueTask";
        var hasReturn = !isAsync
            ? retType.SpecialType != SpecialType.System_Void
            : metaName is "Task`1" or "ValueTask`1";

        var resultTypeName = hasReturn
            ? (retNamed?.TypeArguments.Length > 0
                ? retNamed.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : retType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            : "object";

        // Unique struct name — include all interceptor short names
        var intSuffix = string.Join("_", interceptorTypes.Select(t => InvocationEmitter.Sanitize(t.Name)));
        var structName = InvocationEmitter.BuildStructName(safeSvcName, method);
        structName = $"{structName}_{intSuffix}";

        var interfaceName = hasReturn ? $"IInvocation<{resultTypeName}>" : "IInvocation";

        sb.AppendLine($"struct {structName} : {interfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal readonly {svcFullName} _target;");
        for (int i = 0; i < interceptorTypes.Count; i++)
            sb.AppendLine($"    internal readonly {interceptorTypes[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} _i{i};");
        foreach (var p in method.Parameters)
            sb.AppendLine($"    internal readonly {p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} _{p.Name};");
        sb.AppendLine();

        // Constructor
        var ctorParams = $"({svcFullName} target";
        for (int i = 0; i < interceptorTypes.Count; i++)
        {
            var intName = interceptorTypes[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            ctorParams += $", {intName} i{i}";
        }
        if (method.Parameters.Length > 0)
            ctorParams += ", " + string.Join(", ", method.Parameters.Select(p =>
                $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}"));
        ctorParams += ")";

        sb.AppendLine($"    internal {structName}{ctorParams}");
        sb.AppendLine("    {");
        sb.AppendLine("        _target = target;");
        for (int i = 0; i < interceptorTypes.Count; i++)
            sb.AppendLine($"        _i{i} = i{i};");
        foreach (var p in method.Parameters)
            sb.AppendLine($"        _{p.Name} = {p.Name};");
        if (hasReturn)
            sb.AppendLine("        Result = default!;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public string MethodName => \"{method.Name}\";");
        sb.AppendLine($"    public Type ServiceType => typeof({svcFullName});");
        if (hasReturn)
            sb.AppendLine($"    public {resultTypeName} Result {{ get; set; }}");
        sb.AppendLine();

        var paramArgs = string.Join(", ", method.Parameters.Select(p => $"_{p.Name}"));
        if (isAsync)
        {
            var asyncRet = hasReturn ? $"ValueTask<{resultTypeName}>" : "ValueTask";
            var isOrigValueTask = metaName is "ValueTask" or "ValueTask`1";
            if (hasReturn && !isOrigValueTask)
                sb.AppendLine($"    internal {asyncRet} InvokeTargetAsync() => new(_target.{method.Name}({paramArgs}));");
            else if (hasReturn)
                sb.AppendLine($"    internal {asyncRet} InvokeTargetAsync() => _target.{method.Name}({paramArgs});");
            else if (isOrigValueTask)
                sb.AppendLine($"    internal {asyncRet} InvokeTargetAsync() => _target.{method.Name}({paramArgs});");
            else
                sb.AppendLine($"    internal async {asyncRet} InvokeTargetAsync() => await _target.{method.Name}({paramArgs});");
        }
        else
        {
            if (hasReturn)
                sb.AppendLine($"    internal {resultTypeName} InvokeTarget() => _target.{method.Name}({paramArgs});");
            else
                sb.AppendLine($"    internal void InvokeTarget() => _target.{method.Name}({paramArgs});");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitPropertyStructs(
        StringBuilder sb, string safeSvcName,
        IPropertySymbol prop, INamedTypeSymbol serviceType, List<ITypeSymbol> interceptorTypes)
    {
        var svcFullName = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var intSuffix = string.Join("_", interceptorTypes.Select(t => InvocationEmitter.Sanitize(t.Name)));

        if (prop.GetMethod?.DeclaredAccessibility == Accessibility.Public)
        {
            sb.AppendLine($"struct Invocation_{safeSvcName}_{prop.Name}_Getter_{intSuffix} : IInvocation<{propType}>");
            sb.AppendLine("{");
            sb.AppendLine($"    internal readonly {svcFullName} _target;");
            for (int i = 0; i < interceptorTypes.Count; i++)
                sb.AppendLine($"    internal readonly {interceptorTypes[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} _i{i};");
            sb.AppendLine($"    public string MethodName => \"get_{prop.Name}\";");
            sb.AppendLine($"    public Type ServiceType => typeof({svcFullName});");
            sb.AppendLine($"    public {propType} Result {{ get; set; }}");
            sb.AppendLine($"    internal {propType} InvokeTarget() => _target.{prop.Name};");
            sb.AppendLine("}");
        }

        if (prop.SetMethod?.DeclaredAccessibility == Accessibility.Public && !prop.SetMethod.IsInitOnly)
        {
            sb.AppendLine($"struct Invocation_{safeSvcName}_{prop.Name}_Setter_{intSuffix} : IInvocation");
            sb.AppendLine("{");
            sb.AppendLine($"    internal readonly {svcFullName} _target;");
            for (int i = 0; i < interceptorTypes.Count; i++)
                sb.AppendLine($"    internal readonly {interceptorTypes[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} _i{i};");
            sb.AppendLine($"    internal readonly {propType} _value;");
            sb.AppendLine($"    public string MethodName => \"set_{prop.Name}\";");
            sb.AppendLine($"    public Type ServiceType => typeof({svcFullName});");
            sb.AppendLine($"    internal void InvokeTarget() => _target.{prop.Name} = _value;");
            sb.AppendLine("}");
        }
    }

    private static string EmitMultiWrappers(string safeSvcName, INamedTypeSymbol serviceType, List<ITypeSymbol> interceptorTypes)
    {
        var svcFullName = serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var intSuffix = string.Join("_", interceptorTypes.Select(t => InvocationEmitter.Sanitize(t.Name)));
        var className = $"{PicoAopNames.InterceptedPrefix}{safeSvcName}_{intSuffix}";

        var wrapperParams = string.Join(", ", new[] { $"{svcFullName} inner" }
            .Concat(interceptorTypes.Select((t, i) => $"{t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} i{i}")));

        return
            $"public static partial class {PicoAopNames.WrappersClass}\n" +
            "{\n" +
            $"    public static {svcFullName} Wrap_{safeSvcName}_{intSuffix}({wrapperParams}) =>\n" +
            $"        new {className}(inner, {string.Join(", ", interceptorTypes.Select((_, i) => $"i{i}"))});\n" +
            "}\n";
    }
}
