// <auto-generated/>
#pragma warning disable CS0618

using PicoLog.Abs;

namespace <global namespace>
{
    public static partial class GoldenLogMessages
    {
        public static void UserLoggedIn(this ILogger logger, string userId, string ipAddress)
        {
            logger.Log(LogLevel.Info, new EventId(1001, null), $"User {userId} logged in from {ipAddress}");
        }

        public static void DiskSpaceLow(this ILogger logger, int freeMb)
        {
            logger.Log(LogLevel.Warning, $"Disk space low: {freeMb} MB remaining");
        }

    }
}
