// <auto-generated />
#nullable enable
namespace PicoCfg;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
internal static class PicoCfgBindGeneratedRegistrations
{
    [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
    internal static void Initialize()
    {
        global::PicoCfg.CfgBindRuntime.Register<global::GoldenSettings>(
            contractVersion: global::PicoCfg.CfgBindRuntime.ContractVersion,
            bind: (global::System.Func<global::PicoCfg.Abs.ICfg, string?, global::GoldenSettings>)Bind_0,
            tryBind: (global::PicoCfg.PicoCfgGeneratedTryBindDelegate<global::GoldenSettings>)TryBind_0,
            bindInto: (global::PicoCfg.PicoCfgGeneratedBindIntoDelegate<global::GoldenSettings>)BindInto_0);

    }

    private static global::GoldenSettings Bind_0(global::PicoCfg.Abs.ICfg cfg, string? section)
    {
        var instance = new global::GoldenSettings();
        BindInto_0(cfg, section, instance);
        return instance;
    }

    private static bool TryBind_0(global::PicoCfg.Abs.ICfg cfg, string? section, out global::GoldenSettings value)
    {
        var instance = new global::GoldenSettings();
        if (!TryBindInto_0(cfg, section, instance))
        {
            value = default!;
            return false;
        }

        value = instance;
        return true;
    }

    private static void BindInto_0(global::PicoCfg.Abs.ICfg cfg, string? section, global::GoldenSettings instance)
    {
        var __path_Name = global::PicoCfg.CfgBindRuntime.CombinePath(section, "Name");
        if (cfg.TryGetValue(__path_Name, out var __raw_Name))
        {
            instance.Name = __raw_Name;
        }
        var __path_MaxRetries = global::PicoCfg.CfgBindRuntime.CombinePath(section, "MaxRetries");
        if (cfg.TryGetValue(__path_MaxRetries, out var __raw_MaxRetries))
        {
            if (!global::PicoCfg.CfgBindRuntime.TryParseInt32(__raw_MaxRetries, out var __value_MaxRetries))
            {
                throw global::PicoCfg.CfgBindRuntime.CreateConversionException(__path_MaxRetries, "int", "GoldenSettings.MaxRetries");
            }
            instance.MaxRetries = __value_MaxRetries;
        }
        var __path_EnableFeature = global::PicoCfg.CfgBindRuntime.CombinePath(section, "EnableFeature");
        if (cfg.TryGetValue(__path_EnableFeature, out var __raw_EnableFeature))
        {
            if (!global::PicoCfg.CfgBindRuntime.TryParseBoolean(__raw_EnableFeature, out var __value_EnableFeature))
            {
                throw global::PicoCfg.CfgBindRuntime.CreateConversionException(__path_EnableFeature, "bool", "GoldenSettings.EnableFeature");
            }
            instance.EnableFeature = __value_EnableFeature;
        }
    }

    private static bool TryBindInto_0(global::PicoCfg.Abs.ICfg cfg, string? section, global::GoldenSettings instance)
    {
        var any = false;
        var __path_Name = global::PicoCfg.CfgBindRuntime.CombinePath(section, "Name");
        if (cfg.TryGetValue(__path_Name, out var __raw_Name))
        {
            any = true;
            instance.Name = __raw_Name;
        }
        var __path_MaxRetries = global::PicoCfg.CfgBindRuntime.CombinePath(section, "MaxRetries");
        if (cfg.TryGetValue(__path_MaxRetries, out var __raw_MaxRetries))
        {
            any = true;
            if (!global::PicoCfg.CfgBindRuntime.TryParseInt32(__raw_MaxRetries, out var __value_MaxRetries))
            {
                return false;
            }
            instance.MaxRetries = __value_MaxRetries;
        }
        var __path_EnableFeature = global::PicoCfg.CfgBindRuntime.CombinePath(section, "EnableFeature");
        if (cfg.TryGetValue(__path_EnableFeature, out var __raw_EnableFeature))
        {
            any = true;
            if (!global::PicoCfg.CfgBindRuntime.TryParseBoolean(__raw_EnableFeature, out var __value_EnableFeature))
            {
                return false;
            }
            instance.EnableFeature = __value_EnableFeature;
        }
        return any;
    }

}
