namespace PicoCfg.Gen;

// Renders generated registration and binding code from validated models.
public sealed partial class PicoCfgBindGenerator
{
    private static string Render(IReadOnlyList<TargetModel> targets)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace PicoCfg;");
        sb.AppendLine();
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sb.AppendLine("internal static class PicoCfgBindGeneratedRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        for (var i = 0; i < targets.Count; i++)
        {
            var target = targets[i];
            var typeName = target
                .TargetType
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var bindDelegateType =
                "global::System.Func<global::PicoCfg.Abs.ICfg, string?, " + typeName + ">";
            var tryBindDelegateType =
                "global::PicoCfg.PicoCfgGeneratedTryBindDelegate<" + typeName + ">";
            var bindIntoDelegateType =
                "global::PicoCfg.PicoCfgGeneratedBindIntoDelegate<" + typeName + ">";
            var hasCtor = target.HasPublicParameterlessConstructor
                ? "(" + bindDelegateType + ")Bind_" + i
                : "null";
            var hasTryBind = target.HasPublicParameterlessConstructor
                ? "(" + tryBindDelegateType + ")TryBind_" + i
                : "null";

            sb.Append("        global::PicoCfg.CfgBindRuntime.Register<")
                .Append(typeName)
                .AppendLine(">(");
            sb.AppendLine(
                "            contractVersion: global::PicoCfg.CfgBindRuntime.ContractVersion,"
            );
            sb.Append("            bind: ").Append(hasCtor).AppendLine(",");
            sb.Append("            tryBind: ").Append(hasTryBind).AppendLine(",");
            sb.Append("            bindInto: (")
                .Append(bindIntoDelegateType)
                .Append(")BindInto_")
                .Append(i)
                .AppendLine(");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        for (var i = 0; i < targets.Count; i++)
            AppendTargetMethods(sb, targets[i], i);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendTargetMethods(StringBuilder sb, TargetModel target, int index)
    {
        var typeName = target.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var hasInitOnly = target.Properties.Any(static p => p.RequiresInitializerSyntax);

        if (target.HasPublicParameterlessConstructor)
        {
            if (hasInitOnly)
            {
                AppendBindMethodWithInitOnly(sb, target, index, typeName);
                AppendTryBindMethodWithInitOnly(sb, target, index, typeName);
            }
            else
            {
                sb.Append("    private static ")
                    .Append(typeName)
                    .Append(" Bind_")
                    .Append(index)
                    .AppendLine("(global::PicoCfg.Abs.ICfg cfg, string? section)");
                sb.AppendLine("    {");
                sb.Append("        var instance = new ").Append(typeName).AppendLine("();");
                sb.Append("        BindInto_")
                    .Append(index)
                    .AppendLine("(cfg, section, instance);");
                sb.AppendLine("        return instance;");
                sb.AppendLine("    }");
                sb.AppendLine();

                sb.Append("    private static bool TryBind_")
                    .Append(index)
                    .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, out ")
                    .Append(typeName)
                    .AppendLine(" value)");
                sb.AppendLine("    {");
                sb.Append("        var instance = new ").Append(typeName).AppendLine("();");
                sb.Append("        if (!TryBindInto_")
                    .Append(index)
                    .AppendLine("(cfg, section, instance))");
                sb.AppendLine("        {");
                sb.AppendLine("            value = default!;");
                sb.AppendLine("            return false;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        value = instance;");
                sb.AppendLine("        return true;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        sb.Append("    private static void BindInto_")
            .Append(index)
            .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, ")
            .Append(typeName)
            .AppendLine(" instance)");
        sb.AppendLine("    {");
        foreach (var property in target.Properties)
        {
            if (property.RequiresInitializerSyntax)
                continue;
            AppendBindProperty(sb, target, property, throwOnFailure: true);
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.Append("    private static bool TryBindInto_")
            .Append(index)
            .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, ")
            .Append(typeName)
            .AppendLine(" instance)");
        sb.AppendLine("    {");
        sb.AppendLine("        var any = false;");
        foreach (var property in target.Properties)
        {
            if (property.RequiresInitializerSyntax)
                continue;
            AppendBindProperty(sb, target, property, throwOnFailure: false);
        }
        sb.AppendLine("        return any;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendBindMethodWithInitOnly(
        StringBuilder sb,
        TargetModel target,
        int index,
        string typeName
    )
    {
        sb.Append("    private static ")
            .Append(typeName)
            .Append(" Bind_")
            .Append(index)
            .AppendLine("(global::PicoCfg.Abs.ICfg cfg, string? section)");
        sb.AppendLine("    {");

        AppendInlinePropertyValues(sb, target, throwOnFailure: true, hasAnyVar: false);

        sb.Append("        return new ").Append(typeName).AppendLine();
        sb.AppendLine("        {");
        for (var i = 0; i < target.Properties.Length; i++)
        {
            var property = target.Properties[i];
            var separator = i < target.Properties.Length - 1 ? "," : "";
            sb.Append("            ")
                .Append(property.Name)
                .Append(" = __value_")
                .Append(property.Name)
                .Append(separator)
                .AppendLine();
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendTryBindMethodWithInitOnly(
        StringBuilder sb,
        TargetModel target,
        int index,
        string typeName
    )
    {
        sb.Append("    private static bool TryBind_")
            .Append(index)
            .Append("(global::PicoCfg.Abs.ICfg cfg, string? section, out ")
            .Append(typeName)
            .AppendLine(" value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var any = false;");

        AppendInlinePropertyValues(sb, target, throwOnFailure: false, hasAnyVar: true);

        sb.AppendLine();
        sb.Append("        value = new ").Append(typeName).AppendLine();
        sb.AppendLine("        {");
        for (var i = 0; i < target.Properties.Length; i++)
        {
            var property = target.Properties[i];
            var separator = i < target.Properties.Length - 1 ? "," : "";
            sb.Append("            ")
                .Append(property.Name)
                .Append(" = __value_")
                .Append(property.Name)
                .Append(separator)
                .AppendLine();
        }
        sb.AppendLine("        };");
        sb.AppendLine("        return any;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendInlinePropertyValues(
        StringBuilder sb,
        TargetModel target,
        bool throwOnFailure,
        bool hasAnyVar
    )
    {
        foreach (var property in target.Properties)
        {
            if (property.ScalarKind == ScalarKind.Nested)
            {
                AppendNestedInlineValue(sb, property, hasAnyVar);
                continue;
            }

            if (
                property.ScalarKind
                is ScalarKind.Collection_List
                    or ScalarKind.Collection_Array
                    or ScalarKind.Collection_Dictionary
            )
            {
                AppendCollectionInlineValue(sb, property, hasAnyVar);
                continue;
            }

            var valueName = "__value_" + property.Name;
            var pathName = "__path_" + property.Name;
            var rawName = "__raw_" + property.Name;
            var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
            var targetDisplay = SymbolDisplay.FormatLiteral(
                property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                true
            );
            var memberDisplay = SymbolDisplay.FormatLiteral(
                target.TargetType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                    + "."
                    + property.Name,
                true
            );

            var valueTypeName =
                property.ScalarKind == ScalarKind.String
                    ? "string"
                    : property.IsNullable
                        ? property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                        : property
                            .UnderlyingType
                            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var valueType =
                property.ScalarKind == ScalarKind.String
                    ? property.Type
                    : property.IsNullable
                        ? property.Type
                        : property.UnderlyingType;
            var defaultValue = valueType.IsReferenceType ? "default!" : "default";

            sb.Append("        ")
                .Append(valueTypeName)
                .Append(" ")
                .Append(valueName)
                .Append(" = ")
                .Append(defaultValue)
                .AppendLine(";");

            sb.Append("        var ")
                .Append(pathName)
                .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
                .Append(propertyPathLiteral)
                .AppendLine(");");
            sb.Append("        if (cfg.TryGetValue(")
                .Append(pathName)
                .Append(", out var ")
                .Append(rawName)
                .AppendLine("))");
            sb.AppendLine("        {");

            if (hasAnyVar)
                sb.AppendLine("            any = true;");

            if (property.ScalarKind == ScalarKind.String)
            {
                sb.Append("            ")
                    .Append(valueName)
                    .Append(" = ")
                    .Append(rawName)
                    .AppendLine(";");
            }
            else if (property.IsNullable)
            {
                sb.Append("            if (string.IsNullOrEmpty(").Append(rawName).AppendLine("))");
                sb.AppendLine("            {");
                sb.Append("                ").Append(valueName).AppendLine(" = default!;");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                var parseCall = GetParseCall(
                    property.ScalarKind,
                    rawName,
                    valueName,
                    property
                        .UnderlyingType
                        .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    declareVariable: false
                );
                sb.Append("                if (!").Append(parseCall).AppendLine(")");
                sb.AppendLine("                {");
                if (throwOnFailure)
                {
                    sb.Append(
                            "                    throw global::PicoCfg.CfgBindRuntime.CreateConversionException("
                        )
                        .Append(pathName)
                        .Append(", ")
                        .Append(targetDisplay)
                        .Append(", ")
                        .Append(memberDisplay)
                        .AppendLine(");");
                }
                else
                {
                    sb.AppendLine("                    return false;");
                }
                sb.AppendLine("                }");
                sb.AppendLine("            }");
            }
            else
            {
                var parseCall = GetParseCall(
                    property.ScalarKind,
                    rawName,
                    valueName,
                    property
                        .UnderlyingType
                        .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    declareVariable: false
                );
                sb.Append("            if (!").Append(parseCall).AppendLine(")");
                sb.AppendLine("            {");
                if (throwOnFailure)
                {
                    sb.Append(
                            "                throw global::PicoCfg.CfgBindRuntime.CreateConversionException("
                        )
                        .Append(pathName)
                        .Append(", ")
                        .Append(targetDisplay)
                        .Append(", ")
                        .Append(memberDisplay)
                        .AppendLine(");");
                }
                else
                {
                    sb.AppendLine("                return false;");
                }
                sb.AppendLine("            }");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private static void AppendBindProperty(
        StringBuilder sb,
        TargetModel target,
        PropertyModel property,
        bool throwOnFailure
    )
    {
        if (property.ScalarKind == ScalarKind.Nested)
        {
            AppendNestedBindProperty(sb, property, throwOnFailure);
            return;
        }

        if (
            property.ScalarKind
            is ScalarKind.Collection_List
                or ScalarKind.Collection_Array
                or ScalarKind.Collection_Dictionary
        )
        {
            AppendCollectionBindProperty(sb, property, throwOnFailure);
            return;
        }

        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var targetDisplay = SymbolDisplay.FormatLiteral(
            property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
            true
        );
        var memberDisplay = SymbolDisplay.FormatLiteral(
            target.TargetType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                + "."
                + property.Name,
            true
        );
        var rawName = "__raw_" + property.Name;
        var pathName = "__path_" + property.Name;
        var valueName = "__value_" + property.Name;

        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        if (cfg.TryGetValue(")
            .Append(pathName)
            .Append(", out var ")
            .Append(rawName)
            .AppendLine("))");
        sb.AppendLine("        {");
        if (!throwOnFailure)
            sb.AppendLine("            any = true;");

        if (property.ScalarKind == ScalarKind.String)
        {
            sb.Append("            instance.")
                .Append(property.Name)
                .Append(" = ")
                .Append(rawName)
                .AppendLine(";");
        }
        else if (property.IsNullable)
        {
            sb.Append("            if (string.IsNullOrEmpty(").Append(rawName).AppendLine("))");
            sb.AppendLine("            {");
            sb.Append("                instance.").Append(property.Name).AppendLine(" = null;");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            AppendParseBlock(
                sb,
                property,
                rawName,
                valueName,
                pathName,
                targetDisplay,
                memberDisplay,
                throwOnFailure,
                indent: "                "
            );
            sb.Append("                instance.")
                .Append(property.Name)
                .Append(" = ")
                .Append(valueName)
                .AppendLine(";");
            sb.AppendLine("            }");
        }
        else
        {
            AppendParseBlock(
                sb,
                property,
                rawName,
                valueName,
                pathName,
                targetDisplay,
                memberDisplay,
                throwOnFailure,
                indent: "            "
            );
            sb.Append("            instance.")
                .Append(property.Name)
                .Append(" = ")
                .Append(valueName)
                .AppendLine(";");
        }

        sb.AppendLine("        }");
        if (property.IsRequired)
        {
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.Append("            instance.").Append(property.Name).Append(" = ");
            sb.Append(property.Type.IsReferenceType ? "default!" : "default");
            sb.AppendLine(";");
            sb.AppendLine("        }");
        }
    }

    private static void AppendNestedBindProperty(
        StringBuilder sb,
        PropertyModel property,
        bool throwOnFailure
    )
    {
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);

        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        instance.")
            .Append(property.Name)
            .Append(" = Bind_")
            .Append(property.NestedModelIndex)
            .Append("(")
            .Append(sectionName)
            .AppendLine(", null);");
        if (!throwOnFailure)
            sb.AppendLine("        any = true;");
    }

    private static void AppendNestedInlineValue(
        StringBuilder sb,
        PropertyModel property,
        bool hasAnyVar
    )
    {
        var valueName = "__value_" + property.Name;
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var valueTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.Append("        ")
            .Append(valueTypeName)
            .Append(" ")
            .Append(valueName)
            .AppendLine(" = default!;");
        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        ")
            .Append(valueName)
            .Append(" = Bind_")
            .Append(property.NestedModelIndex)
            .Append("(")
            .Append(sectionName)
            .AppendLine(", null);");
        if (hasAnyVar)
            sb.AppendLine("        any = true;");
        sb.AppendLine();
    }

    private static void AppendCollectionBindProperty(
        StringBuilder sb,
        PropertyModel property,
        bool throwOnFailure
    )
    {
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var isDictionary = property.ScalarKind == ScalarKind.Collection_Dictionary;
        var accName = isDictionary ? "__dict_" + property.Name : "__list_" + property.Name;

        string accTypeFqn;
        if (
            property.ScalarKind == ScalarKind.Collection_Array
            && property.ElementType is { } arrElemType
        )
        {
            var arrElemFqn = arrElemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            accTypeFqn = "global::System.Collections.Generic.List<" + arrElemFqn + ">";
        }
        else
        {
            accTypeFqn = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(accName)
            .Append(" = new ")
            .Append(accTypeFqn)
            .AppendLine("();");

        sb.AppendLine("        for (var __i = 0; ; __i++)");
        sb.AppendLine("        {");

        if (isDictionary)
        {
            sb.Append("            if (!")
                .Append(sectionName)
                .AppendLine(
                    ".TryGetValue(__i.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \":Key\", out var __rawKey))"
                );
            sb.AppendLine("                break;");
            sb.Append("            if (!")
                .Append(sectionName)
                .AppendLine(
                    ".TryGetValue(__i.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \":Value\", out var __rawValue))"
                );
            sb.AppendLine("                break;");

            if (property.CollectionElementNestedIndex >= 0)
            {
                sb.Append("            var __elem_")
                    .Append(property.Name)
                    .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(")
                    .Append(sectionName)
                    .Append(
                        ", __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture));"
                    )
                    .AppendLine();
                sb.Append("            ")
                    .Append(accName)
                    .Append("[__rawKey] = Bind_")
                    .Append(property.CollectionElementNestedIndex)
                    .Append("(__elem_")
                    .Append(property.Name)
                    .AppendLine(", null));");
            }
            else if (
                property.ElementType is { } dictElemType
                && TryGetScalarKind(
                    dictElemType,
                    out var dictElemScalarKind,
                    out var dictElemUnderlyingType
                )
            )
            {
                if (dictElemScalarKind == ScalarKind.String)
                {
                    sb.Append("            ")
                        .Append(accName)
                        .AppendLine("[__rawKey] = __rawValue;");
                }
                else
                {
                    var dictElemFqn = dictElemUnderlyingType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat
                    );
                    var parseCall = GetParseCall(
                        dictElemScalarKind,
                        "__rawValue",
                        "__parsed",
                        dictElemFqn,
                        declareVariable: true
                    );
                    sb.Append("            if (!").Append(parseCall).AppendLine(")");
                    sb.AppendLine("            {");
                    if (throwOnFailure)
                    {
                        sb.Append(
                                "                throw global::PicoCfg.CfgBindRuntime.CreateConversionException("
                            )
                            .Append(pathName)
                            .Append(
                                " + \":\" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture)"
                            )
                            .Append(", ")
                            .Append(
                                SymbolDisplay.FormatLiteral(
                                    property
                                        .Type
                                        .ToDisplayString(
                                            SymbolDisplayFormat.MinimallyQualifiedFormat
                                        ),
                                    true
                                )
                            )
                            .Append(", ")
                            .Append(SymbolDisplay.FormatLiteral(property.Name, true))
                            .AppendLine(");");
                    }
                    else
                    {
                        sb.AppendLine("                return false;");
                    }
                    sb.AppendLine("            }");
                    sb.Append("            ").Append(accName).AppendLine("[__rawKey] = __parsed;");
                }
            }
        }
        else
        {
            sb.Append("            if (!")
                .Append(sectionName)
                .AppendLine(
                    ".TryGetValue(__i.ToString(global::System.Globalization.CultureInfo.InvariantCulture), out var __raw))"
                );
            sb.AppendLine("                break;");

            if (property.CollectionElementNestedIndex >= 0)
            {
                sb.Append("            var __elem_")
                    .Append(property.Name)
                    .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(")
                    .Append(sectionName)
                    .Append(
                        ", __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture));"
                    )
                    .AppendLine();
                sb.Append("            ")
                    .Append(accName)
                    .Append(".Add(Bind_")
                    .Append(property.CollectionElementNestedIndex)
                    .Append("(__elem_")
                    .Append(property.Name)
                    .AppendLine(", null));");
            }
            else if (
                property.ElementType is { } listElemType
                && TryGetScalarKind(
                    listElemType,
                    out var elemScalarKind,
                    out var elemUnderlyingType
                )
            )
            {
                if (elemScalarKind == ScalarKind.String)
                {
                    sb.Append("            ").Append(accName).AppendLine(".Add(__raw);");
                }
                else
                {
                    var elemTypeFqn = elemUnderlyingType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat
                    );
                    var parseCall = GetParseCall(
                        elemScalarKind,
                        "__raw",
                        "__parsed",
                        elemTypeFqn,
                        declareVariable: true
                    );
                    sb.Append("            if (!").Append(parseCall).AppendLine(")");
                    sb.AppendLine("            {");
                    if (throwOnFailure)
                    {
                        sb.Append(
                                "                throw global::PicoCfg.CfgBindRuntime.CreateConversionException("
                            )
                            .Append(pathName)
                            .Append(
                                " + \":\" + __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture)"
                            )
                            .Append(", ")
                            .Append(
                                SymbolDisplay.FormatLiteral(
                                    property
                                        .Type
                                        .ToDisplayString(
                                            SymbolDisplayFormat.MinimallyQualifiedFormat
                                        ),
                                    true
                                )
                            )
                            .Append(", ")
                            .Append(SymbolDisplay.FormatLiteral(property.Name, true))
                            .AppendLine(");");
                    }
                    else
                    {
                        sb.AppendLine("                return false;");
                    }
                    sb.AppendLine("            }");
                    sb.Append("            ").Append(accName).AppendLine(".Add(__parsed);");
                }
            }
        }

        sb.AppendLine("        }");

        if (!throwOnFailure)
            sb.AppendLine("        any = true;");

        if (property.ScalarKind == ScalarKind.Collection_Array)
        {
            sb.Append("        instance.")
                .Append(property.Name)
                .Append(" = ")
                .Append(accName)
                .AppendLine(".ToArray();");
        }
        else
        {
            sb.Append("        instance.")
                .Append(property.Name)
                .Append(" = ")
                .Append(accName)
                .AppendLine(";");
        }
    }

    private static void AppendCollectionInlineValue(
        StringBuilder sb,
        PropertyModel property,
        bool hasAnyVar
    )
    {
        var valueName = "__value_" + property.Name;
        var propertyPathLiteral = SymbolDisplay.FormatLiteral(property.Name, true);
        var pathName = "__path_" + property.Name;
        var sectionName = "__section_" + property.Name;
        var isDictionary = property.ScalarKind == ScalarKind.Collection_Dictionary;
        var accName = isDictionary ? "__dict_" + property.Name : "__list_" + property.Name;
        var valueTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string accTypeFqn;
        if (
            property.ScalarKind == ScalarKind.Collection_Array
            && property.ElementType is { } arrElemType
        )
        {
            var arrElemFqn = arrElemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            accTypeFqn = "global::System.Collections.Generic.List<" + arrElemFqn + ">";
        }
        else
        {
            accTypeFqn = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        sb.Append("        ")
            .Append(valueTypeName)
            .Append(" ")
            .Append(valueName)
            .AppendLine(" = default!;");
        sb.Append("        var ")
            .Append(pathName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CombinePath(section, ")
            .Append(propertyPathLiteral)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(sectionName)
            .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(cfg, ")
            .Append(pathName)
            .AppendLine(");");
        sb.Append("        var ")
            .Append(accName)
            .Append(" = new ")
            .Append(accTypeFqn)
            .AppendLine("();");

        sb.AppendLine("        for (var __i = 0; ; __i++)");
        sb.AppendLine("        {");

        if (isDictionary)
        {
            sb.Append("            if (!")
                .Append(sectionName)
                .AppendLine(
                    ".TryGetValue(__i.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \":Key\", out var __rawKey))"
                );
            sb.AppendLine("                break;");
            sb.Append("            if (!")
                .Append(sectionName)
                .AppendLine(
                    ".TryGetValue(__i.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \":Value\", out var __rawValue))"
                );
            sb.AppendLine("                break;");

            if (property.CollectionElementNestedIndex >= 0)
            {
                sb.Append("            var __elem_")
                    .Append(property.Name)
                    .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(")
                    .Append(sectionName)
                    .Append(
                        ", __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture));"
                    )
                    .AppendLine();
                sb.Append("            ")
                    .Append(accName)
                    .Append("[__rawKey] = Bind_")
                    .Append(property.CollectionElementNestedIndex)
                    .Append("(__elem_")
                    .Append(property.Name)
                    .AppendLine(", null));");
            }
            else if (
                property.ElementType is { } dictElemType
                && TryGetScalarKind(
                    dictElemType,
                    out var dictElemScalarKind,
                    out var dictElemUnderlyingType
                )
            )
            {
                if (dictElemScalarKind == ScalarKind.String)
                {
                    sb.Append("            ")
                        .Append(accName)
                        .AppendLine("[__rawKey] = __rawValue;");
                }
                else
                {
                    var dictElemFqn = dictElemUnderlyingType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat
                    );
                    var parseCall = GetParseCall(
                        dictElemScalarKind,
                        "__rawValue",
                        "__parsed",
                        dictElemFqn,
                        declareVariable: true
                    );
                    sb.Append("            if (!").Append(parseCall).AppendLine(")");
                    sb.AppendLine("            {");
                    sb.AppendLine("                return false;");
                    sb.AppendLine("            }");
                    sb.Append("            ").Append(accName).AppendLine("[__rawKey] = __parsed;");
                }
            }
        }
        else
        {
            sb.Append("            if (!")
                .Append(sectionName)
                .AppendLine(
                    ".TryGetValue(__i.ToString(global::System.Globalization.CultureInfo.InvariantCulture), out var __raw))"
                );
            sb.AppendLine("                break;");

            if (property.CollectionElementNestedIndex >= 0)
            {
                sb.Append("            var __elem_")
                    .Append(property.Name)
                    .Append(" = global::PicoCfg.CfgBindRuntime.CreateScopedView(")
                    .Append(sectionName)
                    .Append(
                        ", __i.ToString(global::System.Globalization.CultureInfo.InvariantCulture));"
                    )
                    .AppendLine();
                sb.Append("            ")
                    .Append(accName)
                    .Append(".Add(Bind_")
                    .Append(property.CollectionElementNestedIndex)
                    .Append("(__elem_")
                    .Append(property.Name)
                    .AppendLine(", null));");
            }
            else if (
                property.ElementType is { } listElemType
                && TryGetScalarKind(
                    listElemType,
                    out var elemScalarKind,
                    out var elemUnderlyingType
                )
            )
            {
                if (elemScalarKind == ScalarKind.String)
                {
                    sb.Append("            ").Append(accName).AppendLine(".Add(__raw);");
                }
                else
                {
                    var elemTypeFqn = elemUnderlyingType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat
                    );
                    var parseCall = GetParseCall(
                        elemScalarKind,
                        "__raw",
                        "__parsed",
                        elemTypeFqn,
                        declareVariable: true
                    );
                    sb.Append("            if (!").Append(parseCall).AppendLine(")");
                    sb.AppendLine("            {");
                    sb.AppendLine("                return false;");
                    sb.AppendLine("            }");
                    sb.Append("            ").Append(accName).AppendLine(".Add(__parsed);");
                }
            }
        }

        sb.AppendLine("        }");

        if (hasAnyVar)
            sb.AppendLine("        any = true;");

        if (property.ScalarKind == ScalarKind.Collection_Array)
        {
            sb.Append("        ")
                .Append(valueName)
                .Append(" = ")
                .Append(accName)
                .AppendLine(".ToArray();");
        }
        else
        {
            sb.Append("        ").Append(valueName).Append(" = ").Append(accName).AppendLine(";");
        }
        sb.AppendLine();
    }

    private static void AppendParseBlock(
        StringBuilder sb,
        PropertyModel property,
        string rawName,
        string valueName,
        string pathName,
        string targetDisplay,
        string memberDisplay,
        bool throwOnFailure,
        string indent
    )
    {
        var targetTypeName = property
            .UnderlyingType
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var parseCall = GetParseCall(property.ScalarKind, rawName, valueName, targetTypeName);

        sb.Append(indent).Append("if (!").Append(parseCall).AppendLine(")");
        sb.Append(indent).AppendLine("{");
        if (throwOnFailure)
        {
            sb.Append(indent)
                .Append("    throw global::PicoCfg.CfgBindRuntime.CreateConversionException(")
                .Append(pathName)
                .Append(", ")
                .Append(targetDisplay)
                .Append(", ")
                .Append(memberDisplay)
                .AppendLine(");");
        }
        else
        {
            sb.Append(indent).AppendLine("    return false;");
        }

        sb.Append(indent).AppendLine("}");
    }

    private static string GetParseCall(
        ScalarKind scalarKind,
        string rawName,
        string valueName,
        string targetTypeName,
        bool declareVariable = true
    ) =>
        scalarKind switch
        {
            ScalarKind.Boolean
                => $"global::PicoCfg.CfgBindRuntime.TryParseBoolean({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Byte
                => $"global::PicoCfg.CfgBindRuntime.TryParseByte({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.SByte
                => $"global::PicoCfg.CfgBindRuntime.TryParseSByte({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Int16
                => $"global::PicoCfg.CfgBindRuntime.TryParseInt16({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.UInt16
                => $"global::PicoCfg.CfgBindRuntime.TryParseUInt16({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Int32
                => $"global::PicoCfg.CfgBindRuntime.TryParseInt32({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.UInt32
                => $"global::PicoCfg.CfgBindRuntime.TryParseUInt32({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Int64
                => $"global::PicoCfg.CfgBindRuntime.TryParseInt64({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.UInt64
                => $"global::PicoCfg.CfgBindRuntime.TryParseUInt64({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Single
                => $"global::PicoCfg.CfgBindRuntime.TryParseSingle({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Double
                => $"global::PicoCfg.CfgBindRuntime.TryParseDouble({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Decimal
                => $"global::PicoCfg.CfgBindRuntime.TryParseDecimal({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Guid
                => $"global::PicoCfg.CfgBindRuntime.TryParseGuid({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Enum
                // AOT-safe: delegates to Enum.Parse(typeof(TEnum), ...) + cast (no Enum.TryParse reflection)
                => $"global::PicoCfg.CfgBindRuntime.TryParseEnum<{targetTypeName}>({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.DateTime
                => $"global::PicoCfg.CfgBindRuntime.TryParseDateTime({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.DateTimeOffset
                => $"global::PicoCfg.CfgBindRuntime.TryParseDateTimeOffset({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.DateOnly
                => $"global::PicoCfg.CfgBindRuntime.TryParseDateOnly({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.TimeOnly
                => $"global::PicoCfg.CfgBindRuntime.TryParseTimeOnly({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.TimeSpan
                => $"global::PicoCfg.CfgBindRuntime.TryParseTimeSpan({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Uri
                => $"global::PicoCfg.CfgBindRuntime.TryParseUri({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.Version
                => $"global::PicoCfg.CfgBindRuntime.TryParseVersion({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            ScalarKind.BigInteger
                => $"global::PicoCfg.CfgBindRuntime.TryParseBigInteger({rawName}, out {(declareVariable ? "var " : "")}{valueName})",
            _ => throw new InvalidOperationException($"Unexpected scalar kind '{scalarKind}'."),
        };
}
