using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Pico.DI.SourceGen;

[Generator]
public class PicoDIIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 注册生成器，不需要特定的语法分析
        context.RegisterPostInitializationOutput(GenerateAotSupportCode);
    }

    private void GenerateAotSupportCode(IncrementalGeneratorPostInitializationContext context)
    {
        // 生成基础的 AOT 支持代码
        var aotCode = GenerateAotSupportCode();
        context.AddSource("Pico.DI.AotSupport.g.cs", SourceText.From(aotCode, Encoding.UTF8));

        // 生成编译时服务注册代码
        var registrationCode = GenerateCompileTimeRegistrationCode();
        context.AddSource("Pico.DI.CompileTimeRegistration.g.cs", SourceText.From(registrationCode, Encoding.UTF8));

        // 生成工厂方法代码
        var factoryCode = GenerateFactoryMethodsCode();
        context.AddSource("Pico.DI.FactoryMethods.g.cs", SourceText.From(factoryCode, Encoding.UTF8));
    }

    private string GenerateAotSupportCode()
    {
        return @"// <auto-generated/>
#nullable enable

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using Pico.DI.Abs;

namespace Pico.DI.Generated;

/// <summary>
/// AOT-friendly service container with compile-time optimizations
/// </summary>
public static class AotServiceSupport
{
    /// <summary>
    /// Registers compile-time known services
    /// </summary>
    public static ISvcContainer RegisterAotServices(this ISvcContainer container)
    {
        // Base framework services
        container.RegisterSingle<ISvcContainer>(container);
        
        // Additional services can be registered here by the source generator
        // based on compile-time analysis
        
        return container;
    }

    /// <summary>
    /// Creates service instances using AOT-friendly methods
    /// </summary>
    public static object? CreateAotService(Type serviceType, ISvcProvider provider)
    {
        // Factory methods will be generated here by the source generator
        // based on compile-time analysis of service implementations
        
        return null; // Fallback to runtime resolution
    }

    /// <summary>
    /// Resolves services using AOT-friendly logic
    /// </summary>
    public static object? ResolveAotService(Type serviceType, ISvcProvider provider)
    {
        return CreateAotService(serviceType, provider);
    }
}

/// <summary>
/// Compile-time service registration helpers
/// </summary>
public static class CompileTimeServiceRegistrations
{
    /// <summary>
    /// Creates an AOT-optimized container with compile-time registrations
    /// </summary>
    public static ISvcContainer CreateAotContainer()
    {
        var container = new Pico.DI.AotSvcContainer();
        return container.RegisterAotServices();
    }
}";
    }

    private string GenerateCompileTimeRegistrationCode()
    {
        return @"// <auto-generated/>
#nullable enable

using Pico.DI.Abs;

namespace Pico.DI.Generated;

/// <summary>
/// Compile-time service registration methods
/// </summary>
public static class GeneratedServiceRegistrations
{
    /// <summary>
    /// Registers services that are known at compile time
    /// </summary>
    public static ISvcContainer RegisterGeneratedServices(this ISvcContainer container)
    {
        // This method will be extended by the source generator
        // to include compile-time discovered services
        
        return container;
    }
}";
    }

    private string GenerateFactoryMethodsCode()
    {
        return @"// <auto-generated/>
#nullable enable

using System;
using Pico.DI.Abs;

namespace Pico.DI.Generated;

/// <summary>
/// Compile-time service factory methods
/// </summary>
public static class GeneratedFactoryMethods
{
    /// <summary>
    /// Creates service instances using compile-time generated factories
    /// </summary>
    public static object? CreateService(Type serviceType, ISvcProvider provider)
    {
        // Factory methods will be generated here by the source generator
        // based on compile-time analysis of service implementations
        
        return null; // Fallback to runtime resolution
    }

    /// <summary>
    /// Resolves services using compile-time generated logic
    /// </summary>
    public static object? ResolveService(Type serviceType, ISvcProvider provider)
    {
        return CreateService(serviceType, provider);
    }
}";
    }
}