namespace PicoAop.Abs;

/// <summary>
/// Provides metadata about the intercepted method invocation.
/// This is a marker interface only — the invocation struct
/// generated by PicoAop.Gen implements it for metadata access,
/// but the actual call path uses function pointers directly.
/// </summary>
public interface IInvocation
{
    /// <summary>Gets the name of the intercepted method.</summary>
    string MethodName { get; }

    /// <summary>Gets the service type being intercepted.</summary>
    Type ServiceType { get; }
}

/// <summary>
/// Provides metadata for invocations with a return value.
/// </summary>
public interface IInvocation<TResult> : IInvocation
{
    /// <summary>Gets or sets the return value of the intercepted method.</summary>
    TResult Result { get; set; }
}
