// <auto-generated/>
#nullable enable
using System.Collections.Frozen;

namespace PicoDI.Generated;

/// <summary>
/// Auto-generated service registrations with AOT-compatible factory methods.
/// Optimized with inlined resolution chains for Transient services.
/// </summary>
public static class GeneratedServiceRegistrations_GoldenFileTest
{
    /// <summary>
    /// Module initializer that registers the generated service configuration under a stable configurator identifier.
    /// This is called automatically when the assembly is loaded, before Main() runs.
    /// </summary>
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void AutoRegisterConfigurator()
    {
        global::PicoDI.SvcContainerAutoConfiguration.RegisterConfigurator(
            "generated::GoldenFileTest::GeneratedServiceRegistrations_GoldenFileTest", static container => ConfigureGeneratedServicesCore(container));
    }

    /// <summary>
    /// Registers all scanned services with pre-compiled factory methods.
    /// This method is auto-generated by scanning Register* method calls in the codebase.
    /// Unlike constructor auto-configuration, this wrapper reapplies the generated registrations on every call.
    /// It marks generated configuration as applied for the container, but does not call Build() or route through TryApplyConfiguration().
    /// </summary>
    public static global::PicoDI.Abs.ISvcContainer ConfigureGeneratedServices(this global::PicoDI.Abs.ISvcContainer container)
    {
        ConfigureGeneratedServicesCore(container);
        global::PicoDI.SvcContainerAutoConfiguration.MarkGeneratedConfigurationApplied(container);
        return container;
    }

    /// <summary>
    /// Core implementation that registers services without calling Build().
    /// Used by Module Initializer to allow additional registrations after auto-configuration.
    /// </summary>
    private static void ConfigureGeneratedServicesCore(global::PicoDI.Abs.ISvcContainer container)
    {
        container.Register(new global::PicoDI.Abs.SvcDescriptor(
            typeof(global::IGoldenService),
            static _ => new global::GoldenService(),
            global::PicoDI.Abs.SvcLifetime.Singleton));

        // IEnumerable<T> registrations for AOT compatibility
        container.Register(new global::PicoDI.Abs.SvcDescriptor(
            typeof(global::System.Collections.Generic.IEnumerable<global::IGoldenService>),
            static scope => global::System.Linq.Enumerable.ToArray(
                global::System.Linq.Enumerable.Cast<global::IGoldenService>(
                    scope.GetServices(typeof(global::IGoldenService)))),
            global::PicoDI.Abs.SvcLifetime.Transient));

    }

    /// <summary>
    /// Pre-built frozen registration cache for zero-allocation Build().
    /// Generated at compile time to eliminate runtime dictionary allocation.
    /// </summary>
    internal static readonly global::System.Collections.Frozen.FrozenDictionary<global::System.Type, global::PicoDI.Abs.SvcDescriptor[]> PrebuiltCache =
        new global::System.Collections.Generic.Dictionary<global::System.Type, global::PicoDI.Abs.SvcDescriptor[]>
        {
            { typeof(global::IGoldenService), new global::PicoDI.Abs.SvcDescriptor[]
            {
                new(typeof(global::IGoldenService), typeof(global::GoldenService), global::PicoDI.Abs.SvcLifetime.Singleton),
            } },
        }.ToFrozenDictionary();

    /// <summary>
    /// High-performance typed resolvers that bypass dictionary lookup.
    /// Use these methods directly for maximum resolution speed.
    /// </summary>
    public static class Resolve
    {
        /// <summary>Resolves IGoldenService with direct factory call.</summary>
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static global::IGoldenService IGoldenService(global::PicoDI.Abs.ISvcScope scope)
        {
            return (global::IGoldenService)scope.GetService(typeof(global::IGoldenService));
        }

    }
}
