namespace PicoDI;

/// <summary>
/// Compile-time interceptor registration methods.
/// These methods are compile-time markers — the actual interceptor wiring
/// is emitted by <c>InterceptorGenerator</c> at build time. At runtime,
/// they return the container unchanged.
/// </summary>
public static class SvcContainerAddInterceptorExtensions
{
    /// <summary>
    /// Registers a global interceptor for all services matching the filter chain
    /// (<c>WhereNamespace</c>, <c>WhereImplements</c>, <c>Except</c>).
    /// This is a compile-time marker — the actual decorator classes are
    /// generated by <c>InterceptorGenerator</c>. At runtime this is a no-op.
    /// </summary>
    /// <typeparam name="TInterceptor">The interceptor type. Must implement <see cref="IInterceptor"/>.</typeparam>
    /// <returns>The container for chaining.</returns>
    public static ISvcContainer AddInterceptor<TInterceptor>(this ISvcContainer container)
        where TInterceptor : class, IInterceptor
    {
        return container;
    }
}
