#nullable enable

namespace PicoLog.Gen;

[Generator]
public sealed class PicoLogMessageGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "PicoLog.Abs.PicoLogMessageAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methodInfos = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) =>
                    node is MethodDeclarationSyntax m && m.Modifiers.Any(SyntaxKind.PartialKeyword),
                transform: static (ctx, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    var methodDecl = (MethodDeclarationSyntax)ctx.TargetNode;
                    var methodSymbol = (IMethodSymbol)ctx.TargetSymbol;
                    var attr = ctx.Attributes[0];

                    var level = (byte)attr.ConstructorArguments[0].Value!;

                    int eventId = 0;
                    string? eventName = null;
                    string? message = null;

                    foreach (var namedArg in attr.NamedArguments)
                    {
                        switch (namedArg.Key)
                        {
                            case "EventId":
                                eventId = (int)namedArg.Value.Value!;
                                break;
                            case "EventName":
                                eventName = (string?)namedArg.Value.Value;
                                break;
                            case "Message":
                                message = (string?)namedArg.Value.Value;
                                break;
                        }
                    }

                    var allParams = methodDecl.ParameterList.Parameters;
                    var skipFirst = HasLoggerFirstParam(allParams.FirstOrDefault());
                    var start = skipFirst ? 1 : 0;

                    var paramDecls = ImmutableArray.CreateBuilder<string>(allParams.Count);
                    var paramNames = ImmutableArray.CreateBuilder<string>(allParams.Count);
                    for (int i = start; i < allParams.Count; i++)
                    {
                        var p = allParams[i];
                        paramDecls.Add($"{p.Type} {p.Identifier.Text}");
                        paramNames.Add(p.Identifier.Text);
                    }

                    var namespaceName = methodSymbol.ContainingNamespace.IsGlobalNamespace
                        ? null
                        : methodSymbol.ContainingNamespace.ToDisplayString();
                    var className = methodSymbol.ContainingType.Name;

                    return new MethodInfo(
                        methodDecl.Identifier.Text,
                        namespaceName,
                        className,
                        paramDecls.ToImmutable(),
                        paramNames.ToImmutable(),
                        level,
                        eventId,
                        eventName,
                        message ?? string.Empty
                    );
                }
            );

        context.RegisterSourceOutput(
            methodInfos.Collect(),
            static (spc, methods) =>
            {
                if (methods.IsEmpty)
                    return;
                spc.AddSource("PicoLogMessage.g.cs", GenerateSource(methods));
            }
        );
    }

    private static bool HasLoggerFirstParam(ParameterSyntax? param)
    {
        if (param is null || param.Modifiers.Count == 0)
            return false;
        if (!param.Modifiers.Any(SyntaxKind.ThisKeyword))
            return false;
        var typeName = param.Type?.ToString().Trim();
        return typeName is "ILogger" or "PicoLog.Abs.ILogger"
            || (typeName is not null && typeName.StartsWith("ILogger<", StringComparison.Ordinal));
    }

    private static string GenerateSource(ImmutableArray<MethodInfo> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS0618");
        sb.AppendLine();
        sb.AppendLine("using PicoLog.Abs;");

        var groups = GroupByClass(methods);
        foreach (var group in groups)
        {
            var first = group.Value[0];
            var hasNamespace = !string.IsNullOrEmpty(first.NamespaceName);
            sb.AppendLine();
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {first.NamespaceName}");
                sb.AppendLine("{");
            }
            sb.AppendLine($"    public static partial class {first.ClassName}");
            sb.AppendLine("    {");

            foreach (var method in group.Value)
            {
                AppendMethod(sb, method);
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            if (hasNamespace)
                sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static Dictionary<string, List<MethodInfo>> GroupByClass(
        ImmutableArray<MethodInfo> methods
    )
    {
        var groups = new Dictionary<string, List<MethodInfo>>();
        foreach (var method in methods)
        {
            var key = method.NamespaceName + "::" + method.ClassName;
            if (!groups.TryGetValue(key, out var list))
            {
                list = new List<MethodInfo>();
                groups[key] = list;
            }
            list.Add(method);
        }
        return groups;
    }

    private static void AppendMethod(StringBuilder sb, MethodInfo method)
    {
        var paramDecl =
            method.ParamDeclarations.Length > 0
                ? ", " + string.Join(", ", method.ParamDeclarations)
                : "";

        var interpolated = InterpolatedStringLiteral(method.Message, method.ParamNames);
        var level = LogLevelExpr(method.Level);

        string call;
        if (method.EventId == 0 && method.EventName is null)
        {
            call = $"logger.Log({level}, {interpolated});";
        }
        else
        {
            call =
                $"logger.Log({level}, new EventId({method.EventId}, {StrLiteral(method.EventName)}), {interpolated});";
        }

        sb.AppendLine(
            $"        public static void {method.MethodName}(this ILogger logger{paramDecl})"
        );
        sb.AppendLine("        {");
        sb.AppendLine($"            {call}");
        sb.AppendLine("        }");
    }

    private static string InterpolatedStringLiteral(
        string template,
        ImmutableArray<string> knownParams
    )
    {
        if (template.Length == 0)
            return "$\"\"";

        var sb = new StringBuilder(template.Length + 16);
        int i = 0;
        while (i < template.Length)
        {
            if (i + 1 < template.Length && template[i] == '{' && template[i + 1] == '{')
            {
                sb.Append("{{");
                i += 2;
                continue;
            }
            if (i + 1 < template.Length && template[i] == '}' && template[i + 1] == '}')
            {
                sb.Append("}}");
                i += 2;
                continue;
            }
            if (template[i] == '{' && IsKnownHole(template, i, knownParams))
            {
                sb.Append('{');
            }
            else if (template[i] == '{')
            {
                sb.Append("{{");
            }
            else if (template[i] == '}' && IsClosingKnownHole(template, i, knownParams))
            {
                sb.Append('}');
            }
            else if (template[i] == '}')
            {
                sb.Append("}}");
            }
            else
            {
                sb.Append(template[i]);
            }
            i++;
        }

        return "$\"" + sb + "\"";
    }

    private static string StripFormatSpecifiers(string holeContent)
    {
        int parenDepth = 0;
        int ternaryDepth = 0;

        for (int i = 0; i < holeContent.Length; i++)
        {
            char c = holeContent[i];
            switch (c)
            {
                case '(':
                case '[':
                    parenDepth++;
                    break;
                case ')':
                case ']':
                    if (parenDepth > 0)
                        parenDepth--;
                    break;
                case '?':
                    // Second '?' of '??' is not a ternary start
                    if (i > 0 && holeContent[i - 1] == '?')
                        break;
                    // Null-conditional (?., ?[) and first '?' of '??' are not ternaries
                    if (i + 1 < holeContent.Length)
                    {
                        char next = holeContent[i + 1];
                        if (next == '.' || next == '[' || next == '?')
                            break;
                    }
                    ternaryDepth++;
                    break;
                case ':':
                    if (ternaryDepth > 0)
                    {
                        ternaryDepth--;
                    }
                    else if (parenDepth == 0)
                    {
                        // Top-level ':' is a format specifier delimiter
                        return holeContent.Substring(0, i);
                    }
                    break;
                case ',':
                    if (parenDepth == 0 && ternaryDepth == 0)
                    {
                        // Top-level ',' is an alignment specifier
                        return holeContent.Substring(0, i);
                    }
                    break;
            }
        }
        return holeContent;
    }

    private static bool IsKnownHole(
        string template,
        int openIndex,
        ImmutableArray<string> knownParams
    )
    {
        var close = template.IndexOf('}', openIndex + 1);
        if (close < 0)
            return false;
        var name = template.Substring(openIndex + 1, close - openIndex - 1).Trim();
        return knownParams.Contains(StripFormatSpecifiers(name));
    }

    private static bool IsClosingKnownHole(
        string template,
        int closeIndex,
        ImmutableArray<string> knownParams
    )
    {
        var open = template.LastIndexOf('{', closeIndex - 1, closeIndex);
        if (open < 0)
            return false;
        var name = template.Substring(open + 1, closeIndex - open - 1).Trim();
        return knownParams.Contains(StripFormatSpecifiers(name));
    }

    private static string LogLevelExpr(byte level) =>
        level switch
        {
            0 => "LogLevel.Emergency",
            1 => "LogLevel.Alert",
            2 => "LogLevel.Critical",
            3 => "LogLevel.Error",
            4 => "LogLevel.Warning",
            5 => "LogLevel.Notice",
            6 => "LogLevel.Info",
            7 => "LogLevel.Debug",
            8 => "LogLevel.Trace",
            _ => $"((LogLevel){level})"
        };

    private static string StrLiteral(string? value) => value is null ? "null" : $"\"{value}\"";

    private readonly struct MethodInfo
    {
        public readonly string MethodName;
        public readonly string NamespaceName;
        public readonly string ClassName;
        public readonly ImmutableArray<string> ParamDeclarations;
        public readonly ImmutableArray<string> ParamNames;
        public readonly byte Level;
        public readonly int EventId;
        public readonly string? EventName;
        public readonly string Message;

        public MethodInfo(
            string methodName,
            string namespaceName,
            string className,
            ImmutableArray<string> paramDeclarations,
            ImmutableArray<string> paramNames,
            byte level,
            int eventId,
            string? eventName,
            string message
        )
        {
            MethodName = methodName;
            NamespaceName = namespaceName;
            ClassName = className;
            ParamDeclarations = paramDeclarations;
            ParamNames = paramNames;
            Level = level;
            EventId = eventId;
            EventName = eventName;
            Message = message;
        }
    }
}
